// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.model;

import ar.com.norrmann.financiera.model.ControlCobrador;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ControlCobrador_Roo_Configurable {
    
    declare @type: ControlCobrador: @Configurable;
    
}
