// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.model;

import ar.com.norrmann.financiera.model.ControlCobrador;
import java.io.Serializable;

privileged aspect ControlCobrador_Roo_Serializable {
    
    declare parents: ControlCobrador implements Serializable;
    
    private static final long ControlCobrador.serialVersionUID = 1L;
    
}
