// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.model;

import ar.com.norrmann.financiera.model.Tasa;
import java.io.Serializable;

privileged aspect Tasa_Roo_Serializable {
    
    declare parents: Tasa implements Serializable;
    
    private static final long Tasa.serialVersionUID = 1L;
    
}
