// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.web;

import ar.com.norrmann.financiera.web.CobradorBean;
import java.io.Serializable;

privileged aspect CobradorBean_Roo_Serializable {
    
    declare parents: CobradorBean implements Serializable;
    
    private static final long CobradorBean.serialVersionUID = 1L;
    
}
