// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.web;

import ar.com.norrmann.financiera.web.CuotaBean;
import java.io.Serializable;

privileged aspect CuotaBean_Roo_Serializable {
    
    declare parents: CuotaBean implements Serializable;
    
    private static final long CuotaBean.serialVersionUID = 1L;
    
}
