// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.financiera.web;

import ar.com.norrmann.financiera.web.TipoCreditoBean;
import java.io.Serializable;

privileged aspect TipoCreditoBean_Roo_Serializable {
    
    declare parents: TipoCreditoBean implements Serializable;
    
    private static final long TipoCreditoBean.serialVersionUID = 1L;
    
}
